# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/*'
    - '.binstubs/*'
    - '.bundle/*'
    - 'config/**/*.yml'
    - '.gems/*'
    - 'vendor/**/*'

inherit_from: .rubocop_todo.yml

