development:
  namespace: dpn-sync-dev
  host: localhost
  port: 6379
  db: 0
  password:

test:
  namespace: dpn-sync-test
  host: localhost
  port: 6379
  db: 1
  password:

production:
  namespace: dpn-sync-prod
  host: localhost
  port: 6379
  db: 2
  password:
