# Files in config/settings/*.yml are merged into config/settings.yml, e.g.
# - the development settings are in config/settings/development.yml
# - the production settings are in config/settings/production.yml
# - the test settings are in config/settings/test.yml

# Any *.local.yml files are merged into the corresponding file, like
# config/settings/test.local.yml is merged into config/settings/test.yml
# which, in turn, is merged into config/settings.yml

log_level: debug

# Settings for DPN::Workers::BagReplication
replication:
  :staging_dir: <%= FileUtils.mkpath(File.join('tmp','dpn_staging')).first %>
  :storage_dir: <%= FileUtils.mkpath(File.join('tmp','dpn_storage')).first %>
