
# Settings for DPN::Workers::BagReplicator
# The 'ssh_identity_file' is blank because the test bag retrieval is a local
# file system transfer that does not require ssh.
replication:
  staging_dir: fixtures/staging
  storage_dir: fixtures/storage
  ssh_identity_file:
